### PR TITLE
Initial refactoring of the ACTPAS Integration Service into a separate…

### PR DESCRIPTION
**Pull request by akinboj**
… Wildfly instance.

### CODE REVIEW

**Review by ruggero-v — APPROVED** [review]
Approval for deployment to TEST, code review to be redone

**Review by ruggero-v — APPROVED** [review]
Approval for deployment to TEST, code review to be redone

**Review by ruggero-v — APPROVED** [review]
Approval for deployment to TEST, code review to be redone

**Review by ruggero-v — APPROVED** [review]
Approval for deployment to TEST, code review to be redone

**Review by ruggero-v — APPROVED** [review]
Approval for deployment to TEST, code review to be redone

**Review by jrschremmer — APPROVED** [review]

**Pull request merged**
